#Launching EC2 instance using Ansible
- hosts: localhost
  gather_facts: false
  tasks:
   - name: create a new ec2 key pair, returns generated private key
     ec2_key:
       name: my_keypair
       region: us-east-1
     register: keyout


   - name: print key
     debug:
       var: keyout

   - name: save key
     copy:
       content: "{{keyout.key.private_key}}"
       dest: ./my_keypair.pem
     when: keyout.changed== True

   - name: start an instance with a public IP address
     amazon.aws.ec2_instance:
       name: "public-compute-instance"
       key_name: "my_keypair"
       #vpc_subnet_id: subnet-5ca1ab1e
       instance_type: t2.micro
       security_group: default
    #  network_interfaces:
    #    - assign_public_ip: true
       image_id: ami-09e6f87a47903347c
       exact_count: 1
       region: us-east-1
       tags:
         Environment: Testing
